name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Check Python packages
      run: |
        python -c "import streamlit; import numpy; import seaborn; print('Packages installed successfully')"

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
